apiVersion: v1
kind: Service
metadata:
  labels:
    app: centreon
  name: centreon-deployment
  namespace: default
spec:
  ports:
  - nodePort: 30010
    port: 80
    protocol: TCP
    targetPort: 80
  selector:
    app: centreon
  sessionAffinity: None
  type: NodePort
